# Generated by Django 4.2.5 on 2023-10-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='country',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='postal_code',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
