# Generated by Django 4.2.5 on 2023-10-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_rename_username_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('after_balance', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'transaction_info',
            },
        ),
    ]
