# Generated by Django 4.2.5 on 2023-10-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('deposit_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'deposit_info',
            },
        ),
        migrations.CreateModel(
            name='WithDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('withdraw_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'withdraw_info',
            },
        ),
    ]
