# Generated by Django 4.2.5 on 2023-10-18 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_deposit_date_alter_withdraw_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='deposit_type',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='withdraw_type',
        ),
        migrations.AddField(
            model_name='deposit',
            name='account',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portal.registration'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='account',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw')], max_length=50),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
