# Generated by Django 4.2.5 on 2023-10-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_remove_deposit_deposit_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='after_balance',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=30),
        ),
    ]
