# Generated by Django 4.2.5 on 2023-10-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_remove_transaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.CharField(max_length=30),
        ),
    ]
