# Generated by Django 4.2.5 on 2023-10-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_deposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
